### ISSUE TITLE
Black gap on bottom of screen

### ISSUE THREAD

**Issue by infernoboy** [artillect/artillect.github.io#1]
There is a black gap that cuts off the bottom portion of the app a little. 

iOS 11.3.1, iPhone 7 Plus

![img_63cdb4874828-1](https://user-images.githubusercontent.com/25857/42727592-e883a776-8777-11e8-94e1-eeab711058bc.jpeg)

**Comment by artillect** [comment]
I'm working on fixing it right now, I'll have an update out really soon.

**Comment by artillect** [comment]
Fixed in  981a11a
