### ISSUE TITLE
Tapping status bar does not scroll to top of view

### ISSUE THREAD

**Issue by infernoboy** [artillect/artillect.github.io#11]
**Describe the bug**
Tapping the status bar does not scroll to the top of the view as it should.

**To Reproduce**
1. Open Settings
2. Scroll down
3. Tap status bar

**Expected behavior**
The view should scroll to the top.

iOS 11.3.1 iPhone 7 Plus

**Comment by infernoboy** [comment]
Noticed this is listed under Projects > To Do. Didn't think to look there first, haven't done much issue reporting. Sorry about that.

**Comment by clubby789** [comment]
Sometimes tapping just below the status bar works for me; not always

**Comment by artillect** [comment]
Fixed in 1.1.0, go ahead and update!
