### ISSUE TITLE
"Done" editing button is cut off

### ISSUE THREAD

**Issue by infernoboy** [artillect/artillect.github.io#2]
The "Done" editing button when icons are in wiggle mode is cut off, but still tappable. Using HomeGesture which makes it show up on non-iPhone X. Not a particularly annoying issue, just letting you know.

iOS 11.3.1, iPhone 7 Plus

![img_e372eccaf6b8-1](https://user-images.githubusercontent.com/25857/42727793-de079b38-877a-11e8-899a-b92bfce14d93.jpeg)

**Comment by artillect** [comment]
Thanks for letting me know! I haven't really designed it for non-X devices but compatibility for LittleX, HomeGestures and other similar tweaks is in the works.

**Comment by artillect** [comment]
I haven't completely fixed it, but in v1.0.1 it'll be completely cut off! That's a little bit better but I'll definitely work towards fixing it.

**Comment by infernoboy** [comment]
Ok, that's fine for now. It is better to hide it completely than to have it look wrong.

**Comment by artillect** [comment]
I think I've fixed it, lemme install LittleX and check.

**Comment by artillect** [comment]
Yep it works!
