### ISSUE TITLE
CardBoard - LittleX conflict

### ISSUE THREAD

**Issue by clubby789** [artillect/artillect.github.io#3]
iPhone 5s, 11.3.1, LittleX installed
LittleX statusbar still appears twice, one slightly higher than the other.

**Comment by artillect** [comment]
Could you send a screenshot of what's going on? I think that I fixed that in the newest update.

**Comment by clubby789** [comment]
I'll install the update and see if it works.

**Comment by clubby789** [comment]
Closed pre-emptively. Bottom is fixed, but top of apps is still obscured by the LittleX status bar.

**Comment by clubby789** [comment]
https://imgur.com/a/mu5HmDv

**Comment by artillect** [comment]
Hmm, Cydia is one app that doesn't play nice with LittleX. I'll disable it in Cydia and any other apps that have issues with it.

Speaking of that, what other apps have the top part of the navbar cut off when LittleX is installed?

**Comment by clubby789** [comment]
Mail is the only one I found while quickly skimming, there may be more.

**Comment by artillect** [comment]
Alright, I'll have that on my radar for sure.

**Comment by clubby789** [comment]
Seems to also affect Snapchat

**Comment by artillect** [comment]
I think this is fixed in 1.1.0, try it out
