### ISSUE TITLE
Cardboard Suggestion: Add preference panel

### ISSUE THREAD

**Issue by clubby789** [artillect/artillect.github.io#4]
iPhone 5s, good looking but many important parts of apps are getting cut off. For example, only half of the Reddit navigation bar is visible.  A preferences pane to edit this would be nice.

**Comment by artillect** [comment]
I've fixed the issue with the bottoms of apps being cut off, but a preference pane will definitely be added in the future. Got any suggestions for options? All I can think of at the moment would be changing the corner radii, adding more color options, options to disable it in certain apps, and other options for compatibility with other tweaks.

**Comment by clubby789** [comment]
Changing the height of the card is one that I thought could be nice.

**Comment by artillect** [comment]
I could definitely do that.

I was also thinking of an "Advanced mode" that makes the background of the app switcher black and makes the home screen into an app switcher card. Expect that in a far future update (probably 1.1 or 1.2).
