### ISSUE TITLE
Issues on iPad devices

### ISSUE THREAD

**Issue by DatNightcat** [artillect/artillect.github.io#5]
The status bar is off in portrait mode, meaning that the time isn’t centered and the battery goes off the screen. In portrait mode, there’s also a really annoying issue where a curved black bar appears in the middle of the screen and you can’t touch what’s behind it, making typing extremely annoying.

Landscape mode is better, but the right corners have a white background.
...now they don’t. But now the status bar won’t show up on the home screen!
Well... now ALL of the corners have a white background!

It’s a mess, but I do like the concept of it.

![8b73c27e-fae8-4104-afcf-dad0b392b2f0](https://user-images.githubusercontent.com/26909213/42728092-433c9fb8-87bb-11e8-875f-a6dadef60323.png)
![3a92adf3-bc58-49c4-a0cd-5d9b34dd74e9](https://user-images.githubusercontent.com/26909213/42728093-4366257c-87bb-11e8-9a78-c65d0df9893b.png)
![47ec7f65-9590-4213-8e7c-0b4d315a50eb](https://user-images.githubusercontent.com/26909213/42728094-438d4d32-87bb-11e8-8efd-7a11b0d805c3.png)
![6b152b36-6e36-4d69-bb2b-fa028c860ea6](https://user-images.githubusercontent.com/26909213/42728095-43afe478-87bb-11e8-881e-b325d92b342e.png)

Screenshots don’t seem to cut off the top corners, so I can’t show what’s happening there.

**Comment by artillect** [comment]
I haven't designed the tweak for iPads but thank you for submitting an issue! I think what's going on is that it keeps the dimensions of your screen from landscape while in portrait mode. Should be a simple enough fix but who knows. I'll definitely look into it.

**Comment by DatNightcat** [comment]
Never mind. It comes back. It seems to just be a random thing that may happen when I respring.

**Comment by artillect** [comment]
Huh, if it keeps acting up lemme know.

**Comment by artillect** [comment]
Seems to be fixed.
