### ISSUE TITLE
Status bar elements change size in Notification Center 

### ISSUE THREAD

**Issue by infernoboy** [artillect/artillect.github.io#7]
When pulling down Notification Center, the status bar elements get slightly larger. This makes the spacing look wrong; the bottom of the status bar items touches the card. 

The status bar size should remain the same. I believe there are tweaks that do this, but it should be incorporated into this one. 

iOS 11.3.1 iPhone 7 Plus

**Comment by artillect** [comment]
I've changed the spacing of the status bar globally but I will definitely work on a more permanent fix to keep the aesthetics looking nice.

**Comment by artillect** [comment]
Fixed in 1.1.0, check it out!
