### ISSUE TITLE
Status bar little too small on iP7+

### ISSUE THREAD

**Issue by ColbyRoark** [artillect/artillect.github.io#8]
Hey there

Downloaded and tested on my iP7+, and the status bar just barely cuts off the icons, crashing them into the “cards.” Feel free to email me for a screenshot showing what I mean!

me@colbyroark.com

**Comment by artillect** [comment]
I think I just fixed this in the newest update, check it out!

**Comment by artillect** [comment]
Should be fixed in 1.1.0, update and check it out!
