### ISSUE TITLE
Full screen photos/video are cut off in portrait mode

### ISSUE THREAD

**Issue by infernoboy** [artillect/artillect.github.io#9]
The top of photos and videos that are full screen in portrait mode have their tops cut off. That portion is not viewable at all while in portrait mode. 

1. Take a screen shot while in portrait mode. 
2. View screenshot in Photos. 
3. Tap photo to hide UI. 

Expected
Either the status bar should hide also or the photo should shrink to fit within the card. 

iOS 11.3.1 iPhone 7 Plus

**Comment by artillect** [comment]
For some reason, some apps don't play nice with full screen. I'll work on a fix.

**Comment by clubby789** [comment]
This also happens in iCleaner. As it usually opens an ad after cleaning, the X button is slightly offscreen, meaning I can't click it and see how much has been cleared

**Comment by artillect** [comment]
The rewrite I'm working on should fix this issue and others. Await an update with maybe an exciting new feature or two!

**Comment by artillect** [comment]
Should be fixed in 1.1.0, go ahead and update!
